language: java
jdk:
 - oraclejdk8
 #- openjdk8

before-install:
- 'wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar'
- 'java -jar BuildTools.jar'

script: mvn clean verify

sudo: false
branches:
  only:
    - master
    - release