language: java
jdk:
 - oraclejdk8
 #- openjdk8

before_install:
- 'git config --global --unset core.autocrlf'
- 'wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar'
- 'java -jar BuildTools.jar -Xmx2G'

script: mvn clean verify

sudo: false
branches:
  only:
    - master
    - release